runtime: go111
instance_class: F1
handlers:
- url: /(oauth|action|command/look|command/looks)
  script: auto
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /([^.]+)$
  static_files: static/\1
  upload: static/([^.]+)$
  mime_type: text/html
- url: /javascripts
  static_dir: static/javascripts
- url: /stylesheets
  static_dir: static/stylesheets
- url: /(.*\.png)$
  static_files: static/\1
  upload: static/.*\.png$
- url: /(.*\.xml)$
  static_files: static/\1
  upload: static/.*\.xml$
