name: Run Script

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    defaults:
      run:
        shell: bash -i {0}
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install sdkman
        run: curl -s "https://get.sdkman.io" | bash
      - name: Install kotlin
        run: sdk install kotlin
      - name: Install kscript
        run: sdk install kscript
      - name: Run script
        run: kscript alfred-looks.kts
      - name: Bundle script
        run: kscript --package alfred-looks.kts

      - uses: actions/upload-artifact@v1
        with:
          name: alfred-looks
          path: ./alfred-looks
